name: wake_arrival
description: A new Flutter project.

publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mapbox_search: ^4.2.2
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  geocoding: ^2.1.0
  geofence_foreground_service: ^1.1.5
  latlng: ^2.0.7
  location: ^5.0.3
  flutter_tts: ^4.2.2
  gap: ^3.0.1
  flutter_bloc: ^9.1.1
  kiwi: ^5.0.1
  objectbox: ^4.1.0
  objectbox_flutter_libs: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  objectbox_generator: ^4.1.0
  build_runner: ^2.4.13
  kiwi_generator: ^4.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/png/
    - assets/audio/

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
