name: wake_arrival
description: A new Flutter project.

publish_to: "none"
version: 0.0.1+2

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mapbox_search: ^4.2.2
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  geocoding: ^2.1.0
  geofence_foreground_service: ^1.1.5
  latlng: ^2.0.7
  location: ^8.0.0
  flutter_tts: ^4.2.2
  flutter_local_notifications: ^17.2.2
  gap: ^3.0.1
  intl: ^0.18.0
  objectbox: ^5.0.4
  objectbox_flutter_libs: ^5.0.4
  path_provider: ^2.1.0
  path: ^1.9.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.13
  objectbox_generator: ^5.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/png/
    - assets/audio/

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
